///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace GracePeriodSaved
{
    public partial class FIREFOX_QA
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_TextInput()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='25 Apr 2016') on item 'ExactEquity1.TextInput'.", repo.ExactEquity1.TextInputInfo);
            Validate.Attribute(repo.ExactEquity1.TextInputInfo, "Text", "25 Apr 2016");
        }

        public void Validate_Cell25Apr2016()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating John Augustines Final Date to Exercise'.", repo.ExactEquity.Flex.Cell25Apr2016Info);
            Validate.Attribute(repo.ExactEquity.Flex.Cell25Apr2016Info, "ColumnIndex", "9");
        }

    }
}