///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GracePeriodSaved
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GracePeriodSavedRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    [RepositoryFolder("4f2c779a-8b56-40cb-b3e9-df2d93a463ca")]
    public partial class GracePeriodSavedRepository : RepoGenBaseFolder
    {
        static GracePeriodSavedRepository instance = new GracePeriodSavedRepository();
        GracePeriodSavedRepositoryFolders.ExactEquityAppFolder _exactequity;
        GracePeriodSavedRepositoryFolders.FirefoxAppFolder _firefox;
        GracePeriodSavedRepositoryFolders.ExplorerAppFolder _explorer;
        GracePeriodSavedRepositoryFolders.FlashNPMBinDebugMainHtmlFlashAppFolder _flashnpmbindebugmainhtmlflash;
        ScrollerInfoClass _scrollerInfo;

        /// <summary>
        /// Gets the singleton class instance representing the GracePeriodSavedRepository element repository.
        /// </summary>
        [RepositoryFolder("4f2c779a-8b56-40cb-b3e9-df2d93a463ca")]
        public static GracePeriodSavedRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GracePeriodSavedRepository() 
            : base("GracePeriodSavedRepository", "/", null, 0, false, "4f2c779a-8b56-40cb-b3e9-df2d93a463ca", ".\\RepositoryImages\\GracePeriodSavedRepository4f2c779a.rximgres")
        {
            _exactequity = new GracePeriodSavedRepositoryFolders.ExactEquityAppFolder(this);
            _firefox = new GracePeriodSavedRepositoryFolders.FirefoxAppFolder(this);
            _explorer = new GracePeriodSavedRepositoryFolders.ExplorerAppFolder(this);
            _flashnpmbindebugmainhtmlflash = new GracePeriodSavedRepositoryFolders.FlashNPMBinDebugMainHtmlFlashAppFolder(this);
            _scrollerInfo = new ScrollerInfoClass(this);
        }

        /// <summary>
        /// The ScrollerInfoClass folder.
        /// </summary>
        [RepositoryItemInfo("d2bd30d1-a980-4098-af5c-7320d7229f90")]
        public class ScrollerInfoClass : RepoItemInfo
        {
            /// <summary>
            /// ScrollerInfoClass class constructor.
            /// </summary>
            public ScrollerInfoClass(RepoGenBaseFolder parentFolder)
                : base(parentFolder, "Scroller", "/dom[1]//div[#'flash']/flexobject[@id='flex']/?/?/container[@type='HBox']//container[@id='_main_HGroup2']/container[@id='captableBox']/?/?/container[@id='tabnavigator']/container[@id='awardsView']/?/?/container[@id='optionPlanViewStack']/container[@caption='activetab']/container[@type='Scroller']", 30000, null, "d2bd30d1-a980-4098-af5c-7320d7229f90")
            { }

            /// <summary>
            /// Gets the Screenshot1 item image.
            /// </summary>
            /// <returns>The Screenshot1 image.</returns>
            [RepositoryImage("1168b3df-d413-4ee8-9bed-723c4d414137")]
            public CompressedImage GetScreenshot1()
            {
                return GetImage("1168b3df-d413-4ee8-9bed-723c4d414137");
            }

            /// <summary>
            /// Gets the Screenshot1 item image.
            /// </summary>
            /// <param name="cropRect">The bounds of the sub-image to return.</param>
            /// <returns>The cropped image.</returns>
            [RepositoryImage("1168b3df-d413-4ee8-9bed-723c4d414137")]
            public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
            {
                return GetImage("1168b3df-d413-4ee8-9bed-723c4d414137", cropRect);
            }
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4f2c779a-8b56-40cb-b3e9-df2d93a463ca")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Scroller item.
        /// </summary>
        [RepositoryItem("d2bd30d1-a980-4098-af5c-7320d7229f90")]
        public virtual Ranorex.Container Scroller
        {
            get
            {
                 return _scrollerInfo.CreateAdapter<Ranorex.Container>(true);
            }
        }

        /// <summary>
        /// The Scroller item info.
        /// </summary>
        [RepositoryItemInfo("d2bd30d1-a980-4098-af5c-7320d7229f90")]
        public virtual ScrollerInfoClass ScrollerInfo
        {
            get
            {
                return _scrollerInfo;
            }
        }

        /// <summary>
        /// The ExactEquity folder.
        /// </summary>
        [RepositoryFolder("d670261f-9849-434a-9bca-e02bdffdd610")]
        public virtual GracePeriodSavedRepositoryFolders.ExactEquityAppFolder ExactEquity
        {
            get { return _exactequity; }
        }

        /// <summary>
        /// The Firefox folder.
        /// </summary>
        [RepositoryFolder("8403e747-abd6-4bde-84ae-20de21d76cad")]
        public virtual GracePeriodSavedRepositoryFolders.FirefoxAppFolder Firefox
        {
            get { return _firefox; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("523108aa-d44e-4e3b-9505-eb8b3343feaf")]
        public virtual GracePeriodSavedRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The FlashNPMBinDebugMainHtmlFlash folder.
        /// </summary>
        [RepositoryFolder("dd5134b2-dfb6-4506-96d8-746712ddb82d")]
        public virtual GracePeriodSavedRepositoryFolders.FlashNPMBinDebugMainHtmlFlashAppFolder FlashNPMBinDebugMainHtmlFlash
        {
            get { return _flashnpmbindebugmainhtmlflash; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    public partial class GracePeriodSavedRepositoryFolders
    {
        /// <summary>
        /// The ExactEquityAppFolder folder.
        /// </summary>
        [RepositoryFolder("d670261f-9849-434a-9bca-e02bdffdd610")]
        public partial class ExactEquityAppFolder : RepoGenBaseFolder
        {
            GracePeriodSavedRepositoryFolders.ContainerMainHGroup2Folder _containermainhgroup2;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _copyrightInfo;
            GraphicInfoClass _graphicInfo;
            RepoItemInfo _spantagvarflashvarseqbaseurleqqaInfo;
            RepoItemInfo _textinputInfo;
            FlexInfoClass _flexInfo;
            RepoItemInfo _twotabsearchtextboxInfo;
            RepoItemInfo _issdiv0Info;

            /// <summary>
            /// Creates a new ExactEquity  folder.
            /// </summary>
            public ExactEquityAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExactEquity", "/dom[1]", parentFolder, 30000, null, false, "d670261f-9849-434a-9bca-e02bdffdd610", "")
            {
                _containermainhgroup2 = new GracePeriodSavedRepositoryFolders.ContainerMainHGroup2Folder(this);
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'Email']", 30000, null, "2ef8d460-2e9c-43af-b8ba-6d593a4b0a00");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", 30000, null, "2dc8d60c-4da6-4a3f-b818-f0d486147e42");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//form[#'loginForm']/?/?/button[@innertext='Log in']", 30000, null, "a0eb750e-a12d-45e7-ab73-c933839fb686");
                _copyrightInfo = new RepoItemInfo(this, "Copyright", ".//div[#'copyright']", 30000, null, "65b93c00-7d10-4c42-ba2c-8fe5e3f1e9b8");
                _graphicInfo = new GraphicInfoClass(this);
                _spantagvarflashvarseqbaseurleqqaInfo = new RepoItemInfo(this, "SpanTagVarFlashVarsEqBaseurlEqqa", "dom[@caption~'^https://qa\\.nasdaqprivatem']/descendant-or-self::*/pre[#'line1']/span[@innertext~'^\\ \\ \\ \\ var\\ flashVars\\ =\\ \"base']", 30000, null, "280783cc-ea27-482b-974c-e7842acf51cd");
                _textinputInfo = new RepoItemInfo(this, "TextInput", ".//div[#'flash']/flexobject[@id='flex']//container[@id='container']//container[@type='HGroup']/container[@id='tabDetails']/container[@id='vboxGrant']//container[@id='boxBoard']/container[@id='boxException']/?/?/text[@type='TextInput']", 30000, null, "ab2f8fb6-ef82-4c3d-b36a-a309a8204733");
                _flexInfo = new FlexInfoClass(this);
                _twotabsearchtextboxInfo = new RepoItemInfo(this, "Twotabsearchtextbox", ".//input[#'twotabsearchtextbox']", 30000, null, "321af9bf-3dfa-4dbb-aa94-617433b2d6d9");
                _issdiv0Info = new RepoItemInfo(this, "IssDiv0", ".//div[#'issDiv0']", 30000, null, "6e0565a4-5245-478e-899a-346ae196ffda");
            }

            /// <summary>
            /// The GraphicInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("8403d213-3740-4769-8987-d68d783d81f6")]
            public class GraphicInfoClass : RepoItemInfo
            {
                /// <summary>
                /// GraphicInfoClass class constructor.
                /// </summary>
                public GraphicInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Graphic", ".//object[#'main']/element[@class='GeckoPluginWindow']/picture[6]", 30000, null, "8403d213-3740-4769-8987-d68d783d81f6")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("be830dae-a773-4708-885f-b634f0d0737d")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("be830dae-a773-4708-885f-b634f0d0737d");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("be830dae-a773-4708-885f-b634f0d0737d")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("be830dae-a773-4708-885f-b634f0d0737d", cropRect);
                }
            }

            /// <summary>
            /// The FlexInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("1e85fe78-9211-41ff-9c1e-85beeeb8e99d")]
            public class FlexInfoClass : RepoItemInfo
            {
                /// <summary>
                /// FlexInfoClass class constructor.
                /// </summary>
                public FlexInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Flex", ".//embed[#'flex']", 30000, null, "1e85fe78-9211-41ff-9c1e-85beeeb8e99d")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("09ec22e7-e78b-4454-8fcf-94efbba11723")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("09ec22e7-e78b-4454-8fcf-94efbba11723");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("09ec22e7-e78b-4454-8fcf-94efbba11723")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("09ec22e7-e78b-4454-8fcf-94efbba11723", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d670261f-9849-434a-9bca-e02bdffdd610")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d670261f-9849-434a-9bca-e02bdffdd610")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("2ef8d460-2e9c-43af-b8ba-6d593a4b0a00")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("2ef8d460-2e9c-43af-b8ba-6d593a4b0a00")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("2dc8d60c-4da6-4a3f-b818-f0d486147e42")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("2dc8d60c-4da6-4a3f-b818-f0d486147e42")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("a0eb750e-a12d-45e7-ab73-c933839fb686")]
            public virtual Ranorex.ButtonTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("a0eb750e-a12d-45e7-ab73-c933839fb686")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Copyright item.
            /// </summary>
            [RepositoryItem("65b93c00-7d10-4c42-ba2c-8fe5e3f1e9b8")]
            public virtual Ranorex.DivTag Copyright
            {
                get
                {
                    return _copyrightInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Copyright item info.
            /// </summary>
            [RepositoryItemInfo("65b93c00-7d10-4c42-ba2c-8fe5e3f1e9b8")]
            public virtual RepoItemInfo CopyrightInfo
            {
                get
                {
                    return _copyrightInfo;
                }
            }

            /// <summary>
            /// The Graphic item.
            /// </summary>
            [RepositoryItem("8403d213-3740-4769-8987-d68d783d81f6")]
            public virtual Ranorex.Picture Graphic
            {
                get
                {
                    return _graphicInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic item info.
            /// </summary>
            [RepositoryItemInfo("8403d213-3740-4769-8987-d68d783d81f6")]
            public virtual GraphicInfoClass GraphicInfo
            {
                get
                {
                    return _graphicInfo;
                }
            }

            /// <summary>
            /// The SpanTagVarFlashVarsEqBaseurlEqqa item.
            /// </summary>
            [RepositoryItem("280783cc-ea27-482b-974c-e7842acf51cd")]
            public virtual Ranorex.SpanTag SpanTagVarFlashVarsEqBaseurlEqqa
            {
                get
                {
                    return _spantagvarflashvarseqbaseurleqqaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagVarFlashVarsEqBaseurlEqqa item info.
            /// </summary>
            [RepositoryItemInfo("280783cc-ea27-482b-974c-e7842acf51cd")]
            public virtual RepoItemInfo SpanTagVarFlashVarsEqBaseurlEqqaInfo
            {
                get
                {
                    return _spantagvarflashvarseqbaseurleqqaInfo;
                }
            }

            /// <summary>
            /// The TextInput item.
            /// </summary>
            [RepositoryItem("ab2f8fb6-ef82-4c3d-b36a-a309a8204733")]
            public virtual Ranorex.Text TextInput
            {
                get
                {
                    return _textinputInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextInput item info.
            /// </summary>
            [RepositoryItemInfo("ab2f8fb6-ef82-4c3d-b36a-a309a8204733")]
            public virtual RepoItemInfo TextInputInfo
            {
                get
                {
                    return _textinputInfo;
                }
            }

            /// <summary>
            /// The Flex item.
            /// </summary>
            [RepositoryItem("1e85fe78-9211-41ff-9c1e-85beeeb8e99d")]
            public virtual Ranorex.EmbedTag Flex
            {
                get
                {
                    return _flexInfo.CreateAdapter<Ranorex.EmbedTag>(true);
                }
            }

            /// <summary>
            /// The Flex item info.
            /// </summary>
            [RepositoryItemInfo("1e85fe78-9211-41ff-9c1e-85beeeb8e99d")]
            public virtual FlexInfoClass FlexInfo
            {
                get
                {
                    return _flexInfo;
                }
            }

            /// <summary>
            /// The Twotabsearchtextbox item.
            /// </summary>
            [RepositoryItem("321af9bf-3dfa-4dbb-aa94-617433b2d6d9")]
            public virtual Ranorex.InputTag Twotabsearchtextbox
            {
                get
                {
                    return _twotabsearchtextboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Twotabsearchtextbox item info.
            /// </summary>
            [RepositoryItemInfo("321af9bf-3dfa-4dbb-aa94-617433b2d6d9")]
            public virtual RepoItemInfo TwotabsearchtextboxInfo
            {
                get
                {
                    return _twotabsearchtextboxInfo;
                }
            }

            /// <summary>
            /// The IssDiv0 item.
            /// </summary>
            [RepositoryItem("6e0565a4-5245-478e-899a-346ae196ffda")]
            public virtual Ranorex.DivTag IssDiv0
            {
                get
                {
                    return _issdiv0Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The IssDiv0 item info.
            /// </summary>
            [RepositoryItemInfo("6e0565a4-5245-478e-899a-346ae196ffda")]
            public virtual RepoItemInfo IssDiv0Info
            {
                get
                {
                    return _issdiv0Info;
                }
            }

            /// <summary>
            /// The ContainerMainHGroup2 folder.
            /// </summary>
            [RepositoryFolder("e3ffb7e6-f0e5-463c-8e4c-17e6ef64dfdd")]
            public virtual GracePeriodSavedRepositoryFolders.ContainerMainHGroup2Folder ContainerMainHGroup2
            {
                get { return _containermainhgroup2; }
            }
        }

        /// <summary>
        /// The ContainerMainHGroup2Folder folder.
        /// </summary>
        [RepositoryFolder("e3ffb7e6-f0e5-463c-8e4c-17e6ef64dfdd")]
        public partial class ContainerMainHGroup2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _grants1Info;
            RepoItemInfo _optionplan2011aug112Info;
            RepoItemInfo _textlineInfo;
            RepoItemInfo _optionplan2011aug11Info;
            RepoItemInfo _options1Info;
            Scroller1InfoClass _scroller1Info;
            RepoItemInfo _newitemInfo;
            RepoItemInfo _newitem1Info;

            /// <summary>
            /// Creates a new ContainerMainHGroup2  folder.
            /// </summary>
            public ContainerMainHGroup2Folder(RepoGenBaseFolder parentFolder) :
                    base("ContainerMainHGroup2", ".//div[#'flash']/flexobject[@id='flex']/?/?/container[@type='HBox']//container[@id='_main_HGroup2']", parentFolder, 30000, null, false, "e3ffb7e6-f0e5-463c-8e4c-17e6ef64dfdd", "")
            {
                _grants1Info = new RepoItemInfo(this, "Grants1", "container[3]/container[@id='navigationTree']//container[@id='_NavigationTree_Group4']/tree[@automationname='sidebarNavigation']/treeitem[@text='Grants']", 30000, null, "ad5db1d7-2865-48c8-8443-90bd1a50e2b6");
                _optionplan2011aug112Info = new RepoItemInfo(this, "OptionPlan2011Aug112", "dom[@caption~'^file:///C:/NQ/exact_equit']//object[#'main']/?/?/tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename='Option Plan 2011 (Aug 11)']", 30000, null, "545cc68b-7937-4a2c-ad13-ff16820b39b5");
                _textlineInfo = new RepoItemInfo(this, "TextLine", "container[@id='captableBox']//container[@id='awardsView']/?/?/container[@id='optionPlanViewStack']/container[@caption='activetab']/?/?/table[@id='optionsDataGrid']/row[@index='1']/cell[@text='Jane Corsow']/text[@type='TextLine']", 30000, null, "b0acf22b-2303-4f71-bbf5-ed532f5b8a39");
                _optionplan2011aug11Info = new RepoItemInfo(this, "OptionPlan2011Aug11", "container[3]/container[@id='navigationTree']//container[@id='_NavigationTree_Group4']/tree[@automationname='sidebarNavigation']/treeitem[@text='Grants']/treeitem[@text='Option Plan 2011 (Aug 11)']", 30000, null, "a0471bee-9b2f-4b16-b115-7ffeaab8206d");
                _options1Info = new RepoItemInfo(this, "Options1", "container[@id='captableBox']/?/?/container[@id='tabnavigator']/container[@id='awardsView']/?/?/element[@id='tabBar']/container[@id='dataGroup']/?/?/text[@caption='Options']", 30000, null, "dcdb8015-34b0-4099-a2f6-e7fb3e03b946");
                _scroller1Info = new Scroller1InfoClass(this);
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "b80569e1-9805-4569-8632-044613aad710");
                _newitem1Info = new RepoItemInfo(this, "NewItem1", "element", 30000, null, "4d256d56-9713-49cb-805a-3c9140d8ced3");
            }

            /// <summary>
            /// The Scroller1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("793ada13-2105-4bac-ac2d-70bc40f27be8")]
            public class Scroller1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// Scroller1InfoClass class constructor.
                /// </summary>
                public Scroller1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Scroller1", "container[@id='captableBox']/?/?/container[@id='tabnavigator']/container[@id='awardsView']/container[@type='Scroller']", 30000, null, "793ada13-2105-4bac-ac2d-70bc40f27be8")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("939f3b74-48c8-4342-b23e-b80a7a546c46")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("939f3b74-48c8-4342-b23e-b80a7a546c46");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("939f3b74-48c8-4342-b23e-b80a7a546c46")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("939f3b74-48c8-4342-b23e-b80a7a546c46", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3ffb7e6-f0e5-463c-8e4c-17e6ef64dfdd")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3ffb7e6-f0e5-463c-8e4c-17e6ef64dfdd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Grants1 item.
            /// </summary>
            [RepositoryItem("ad5db1d7-2865-48c8-8443-90bd1a50e2b6")]
            public virtual Ranorex.TreeItem Grants1
            {
                get
                {
                    return _grants1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Grants1 item info.
            /// </summary>
            [RepositoryItemInfo("ad5db1d7-2865-48c8-8443-90bd1a50e2b6")]
            public virtual RepoItemInfo Grants1Info
            {
                get
                {
                    return _grants1Info;
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug112 item.
            /// </summary>
            [RepositoryItem("545cc68b-7937-4a2c-ad13-ff16820b39b5")]
            public virtual Ranorex.TreeItem OptionPlan2011Aug112
            {
                get
                {
                    return _optionplan2011aug112Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug112 item info.
            /// </summary>
            [RepositoryItemInfo("545cc68b-7937-4a2c-ad13-ff16820b39b5")]
            public virtual RepoItemInfo OptionPlan2011Aug112Info
            {
                get
                {
                    return _optionplan2011aug112Info;
                }
            }

            /// <summary>
            /// The TextLine item.
            /// </summary>
            [RepositoryItem("b0acf22b-2303-4f71-bbf5-ed532f5b8a39")]
            public virtual Ranorex.Text TextLine
            {
                get
                {
                    return _textlineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextLine item info.
            /// </summary>
            [RepositoryItemInfo("b0acf22b-2303-4f71-bbf5-ed532f5b8a39")]
            public virtual RepoItemInfo TextLineInfo
            {
                get
                {
                    return _textlineInfo;
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug11 item.
            /// </summary>
            [RepositoryItem("a0471bee-9b2f-4b16-b115-7ffeaab8206d")]
            public virtual Ranorex.TreeItem OptionPlan2011Aug11
            {
                get
                {
                    return _optionplan2011aug11Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug11 item info.
            /// </summary>
            [RepositoryItemInfo("a0471bee-9b2f-4b16-b115-7ffeaab8206d")]
            public virtual RepoItemInfo OptionPlan2011Aug11Info
            {
                get
                {
                    return _optionplan2011aug11Info;
                }
            }

            /// <summary>
            /// The Options1 item.
            /// </summary>
            [RepositoryItem("dcdb8015-34b0-4099-a2f6-e7fb3e03b946")]
            public virtual Ranorex.Text Options1
            {
                get
                {
                    return _options1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Options1 item info.
            /// </summary>
            [RepositoryItemInfo("dcdb8015-34b0-4099-a2f6-e7fb3e03b946")]
            public virtual RepoItemInfo Options1Info
            {
                get
                {
                    return _options1Info;
                }
            }

            /// <summary>
            /// The Scroller1 item.
            /// </summary>
            [RepositoryItem("793ada13-2105-4bac-ac2d-70bc40f27be8")]
            public virtual Ranorex.Container Scroller1
            {
                get
                {
                    return _scroller1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Scroller1 item info.
            /// </summary>
            [RepositoryItemInfo("793ada13-2105-4bac-ac2d-70bc40f27be8")]
            public virtual Scroller1InfoClass Scroller1Info
            {
                get
                {
                    return _scroller1Info;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("b80569e1-9805-4569-8632-044613aad710")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("b80569e1-9805-4569-8632-044613aad710")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }

            /// <summary>
            /// The NewItem1 item.
            /// </summary>
            [RepositoryItem("4d256d56-9713-49cb-805a-3c9140d8ced3")]
            public virtual Ranorex.Unknown NewItem1
            {
                get
                {
                    return _newitem1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem1 item info.
            /// </summary>
            [RepositoryItemInfo("4d256d56-9713-49cb-805a-3c9140d8ced3")]
            public virtual RepoItemInfo NewItem1Info
            {
                get
                {
                    return _newitem1Info;
                }
            }
        }

        /// <summary>
        /// The FirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("8403e747-abd6-4bde-84ae-20de21d76cad")]
        public partial class FirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viewpagesourceInfo;
            RepoItemInfo _copyInfo;

            /// <summary>
            /// Creates a new Firefox  folder.
            /// </summary>
            public FirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Firefox", "/contextmenu[@processname='firefox']", parentFolder, 30000, null, true, "8403e747-abd6-4bde-84ae-20de21d76cad", "")
            {
                _viewpagesourceInfo = new RepoItemInfo(this, "ViewPageSource", "?/?/menuitem[@accessiblename='View Page Source']", 30000, null, "b86fcd48-f9c6-4ad6-a0ca-8b84def053ca");
                _copyInfo = new RepoItemInfo(this, "Copy", "?/?/menuitem[@accessiblename='Copy']", 30000, null, "4b127164-4572-4c94-a141-f39d6b6b690f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8403e747-abd6-4bde-84ae-20de21d76cad")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8403e747-abd6-4bde-84ae-20de21d76cad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewPageSource item.
            /// </summary>
            [RepositoryItem("b86fcd48-f9c6-4ad6-a0ca-8b84def053ca")]
            public virtual Ranorex.MenuItem ViewPageSource
            {
                get
                {
                    return _viewpagesourceInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ViewPageSource item info.
            /// </summary>
            [RepositoryItemInfo("b86fcd48-f9c6-4ad6-a0ca-8b84def053ca")]
            public virtual RepoItemInfo ViewPageSourceInfo
            {
                get
                {
                    return _viewpagesourceInfo;
                }
            }

            /// <summary>
            /// The Copy item.
            /// </summary>
            [RepositoryItem("4b127164-4572-4c94-a141-f39d6b6b690f")]
            public virtual Ranorex.MenuItem Copy
            {
                get
                {
                    return _copyInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Copy item info.
            /// </summary>
            [RepositoryItemInfo("4b127164-4572-4c94-a141-f39d6b6b690f")]
            public virtual RepoItemInfo CopyInfo
            {
                get
                {
                    return _copyInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("523108aa-d44e-4e3b-9505-eb8b3343feaf")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _flashnpmbindebugmainhtmlflashInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "523108aa-d44e-4e3b-9505-eb8b3343feaf", "")
            {
                _flashnpmbindebugmainhtmlflashInfo = new RepoItemInfo(this, "FlashNPMBinDebugMainHtmlFlash", "?/?/container[@caption='Running applications']/?/?/toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Flash\\ -\\ NPM/bin-debug/mai']", 30000, null, "7613410a-ba04-486d-8f37-b55a8e5619e6");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "e2d65dde-8d30-4513-9810-33fb825a03e2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("523108aa-d44e-4e3b-9505-eb8b3343feaf")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("523108aa-d44e-4e3b-9505-eb8b3343feaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FlashNPMBinDebugMainHtmlFlash item.
            /// </summary>
            [RepositoryItem("7613410a-ba04-486d-8f37-b55a8e5619e6")]
            public virtual Ranorex.Button FlashNPMBinDebugMainHtmlFlash
            {
                get
                {
                    return _flashnpmbindebugmainhtmlflashInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FlashNPMBinDebugMainHtmlFlash item info.
            /// </summary>
            [RepositoryItemInfo("7613410a-ba04-486d-8f37-b55a8e5619e6")]
            public virtual RepoItemInfo FlashNPMBinDebugMainHtmlFlashInfo
            {
                get
                {
                    return _flashnpmbindebugmainhtmlflashInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("e2d65dde-8d30-4513-9810-33fb825a03e2")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("e2d65dde-8d30-4513-9810-33fb825a03e2")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The FlashNPMBinDebugMainHtmlFlashAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd5134b2-dfb6-4506-96d8-746712ddb82d")]
        public partial class FlashNPMBinDebugMainHtmlFlashAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mainhtmlInfo;
            RepoItemInfo _styledtextInfo;

            /// <summary>
            /// Creates a new FlashNPMBinDebugMainHtmlFlash  folder.
            /// </summary>
            public FlashNPMBinDebugMainHtmlFlashAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FlashNPMBinDebugMainHtmlFlash", "/form[@title~'^Flash\\ -\\ NPM/bin-debug/mai']", parentFolder, 30000, null, false, "dd5134b2-dfb6-4506-96d8-746712ddb82d", "")
            {
                _mainhtmlInfo = new RepoItemInfo(this, "MainHtml", "container[@type='Composite']/container/container[5]/?/?/tabpage[@title='main.html']", 30000, null, "bea80ecb-f754-4fe0-8f0b-9d69c2183251");
                _styledtextInfo = new RepoItemInfo(this, "StyledText", "container[@type='Composite']/container/container[5]/container[@type='Composite']/container/container[@type='Composite']/container[@type='Composite']/?/?/text[@type='StyledText']", 30000, null, "ad68e456-0333-44e3-afe8-8753e763e1b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd5134b2-dfb6-4506-96d8-746712ddb82d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd5134b2-dfb6-4506-96d8-746712ddb82d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainHtml item.
            /// </summary>
            [RepositoryItem("bea80ecb-f754-4fe0-8f0b-9d69c2183251")]
            public virtual Ranorex.TabPage MainHtml
            {
                get
                {
                    return _mainhtmlInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MainHtml item info.
            /// </summary>
            [RepositoryItemInfo("bea80ecb-f754-4fe0-8f0b-9d69c2183251")]
            public virtual RepoItemInfo MainHtmlInfo
            {
                get
                {
                    return _mainhtmlInfo;
                }
            }

            /// <summary>
            /// The StyledText item.
            /// </summary>
            [RepositoryItem("ad68e456-0333-44e3-afe8-8753e763e1b3")]
            public virtual Ranorex.Text StyledText
            {
                get
                {
                    return _styledtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StyledText item info.
            /// </summary>
            [RepositoryItemInfo("ad68e456-0333-44e3-afe8-8753e763e1b3")]
            public virtual RepoItemInfo StyledTextInfo
            {
                get
                {
                    return _styledtextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}