///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GracePeriodSaved
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NewRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    [RepositoryFolder("d223755f-9baf-42e7-8cd4-0cb5aac85329")]
    public partial class NewRepository : RepoGenBaseFolder
    {
        static NewRepository instance = new NewRepository();
        NewRepositoryFolders.ExactEquityAppFolder _exactequity;
        NewRepositoryFolders.FileCNQExactEquityFlexClientCAppFolder _filecnqexactequityflexclientc;
        NewRepositoryFolders.ExactEquity1AppFolder _exactequity1;
        NewRepositoryFolders.FirefoxAppFolder _firefox;
        NewRepositoryFolders.ExplorerAppFolder _explorer;
        NewRepositoryFolders.FlashNPMBinDebugMainHtmlFlashAppFolder _flashnpmbindebugmainhtmlflash;
        NewRepositoryFolders.ExactEquity2AppFolder _exactequity2;
        NewRepositoryFolders.UltimateBotGamerIDDarrenDeluxeDaAppFolder _ultimatebotgameriddarrendeluxeda;
        NewRepositoryFolders.ScreencastOMaticAppFolder _screencastomatic;

        /// <summary>
        /// Gets the singleton class instance representing the NewRepository element repository.
        /// </summary>
        [RepositoryFolder("d223755f-9baf-42e7-8cd4-0cb5aac85329")]
        public static NewRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NewRepository() 
            : base("NewRepository", "/", null, 0, false, "d223755f-9baf-42e7-8cd4-0cb5aac85329", ".\\RepositoryImages\\NewRepositoryd223755f.rximgres")
        {
            _exactequity = new NewRepositoryFolders.ExactEquityAppFolder(this);
            _filecnqexactequityflexclientc = new NewRepositoryFolders.FileCNQExactEquityFlexClientCAppFolder(this);
            _exactequity1 = new NewRepositoryFolders.ExactEquity1AppFolder(this);
            _firefox = new NewRepositoryFolders.FirefoxAppFolder(this);
            _explorer = new NewRepositoryFolders.ExplorerAppFolder(this);
            _flashnpmbindebugmainhtmlflash = new NewRepositoryFolders.FlashNPMBinDebugMainHtmlFlashAppFolder(this);
            _exactequity2 = new NewRepositoryFolders.ExactEquity2AppFolder(this);
            _ultimatebotgameriddarrendeluxeda = new NewRepositoryFolders.UltimateBotGamerIDDarrenDeluxeDaAppFolder(this);
            _screencastomatic = new NewRepositoryFolders.ScreencastOMaticAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d223755f-9baf-42e7-8cd4-0cb5aac85329")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ExactEquity folder.
        /// </summary>
        [RepositoryFolder("fc1b5049-d13c-46b7-8c1d-f37a10def147")]
        public virtual NewRepositoryFolders.ExactEquityAppFolder ExactEquity
        {
            get { return _exactequity; }
        }

        /// <summary>
        /// The FileCNQExactEquityFlexClientC folder.
        /// </summary>
        [RepositoryFolder("525214a1-bbb3-4596-aa54-8169c8628f32")]
        public virtual NewRepositoryFolders.FileCNQExactEquityFlexClientCAppFolder FileCNQExactEquityFlexClientC
        {
            get { return _filecnqexactequityflexclientc; }
        }

        /// <summary>
        /// The ExactEquity1 folder.
        /// </summary>
        [RepositoryFolder("cf552641-354c-4658-ab2c-145d09c35e82")]
        public virtual NewRepositoryFolders.ExactEquity1AppFolder ExactEquity1
        {
            get { return _exactequity1; }
        }

        /// <summary>
        /// The Firefox folder.
        /// </summary>
        [RepositoryFolder("0b805b63-c5af-49c9-96b0-876b404025ee")]
        public virtual NewRepositoryFolders.FirefoxAppFolder Firefox
        {
            get { return _firefox; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("6c173280-751c-44a1-903f-a0729adbf55b")]
        public virtual NewRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The FlashNPMBinDebugMainHtmlFlash folder.
        /// </summary>
        [RepositoryFolder("259f752b-09dc-4fc8-8965-8d53ebca8fae")]
        public virtual NewRepositoryFolders.FlashNPMBinDebugMainHtmlFlashAppFolder FlashNPMBinDebugMainHtmlFlash
        {
            get { return _flashnpmbindebugmainhtmlflash; }
        }

        /// <summary>
        /// The ExactEquity2 folder.
        /// </summary>
        [RepositoryFolder("1cc404cd-ea2f-4df6-a540-a3d5aa1741fe")]
        public virtual NewRepositoryFolders.ExactEquity2AppFolder ExactEquity2
        {
            get { return _exactequity2; }
        }

        /// <summary>
        /// The UltimateBotGamerIDDarrenDeluxeDa folder.
        /// </summary>
        [RepositoryFolder("771f4671-c51b-4392-8c9f-061bc380314d")]
        public virtual NewRepositoryFolders.UltimateBotGamerIDDarrenDeluxeDaAppFolder UltimateBotGamerIDDarrenDeluxeDa
        {
            get { return _ultimatebotgameriddarrendeluxeda; }
        }

        /// <summary>
        /// The ScreencastOMatic folder.
        /// </summary>
        [RepositoryFolder("d5e2a6cc-a326-4f39-9ed5-e99169ced137")]
        public virtual NewRepositoryFolders.ScreencastOMaticAppFolder ScreencastOMatic
        {
            get { return _screencastomatic; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    public partial class NewRepositoryFolders
    {
        /// <summary>
        /// The ExactEquityAppFolder folder.
        /// </summary>
        [RepositoryFolder("fc1b5049-d13c-46b7-8c1d-f37a10def147")]
        public partial class ExactEquityAppFolder : RepoGenBaseFolder
        {
            NewRepositoryFolders.FlexFolder _flex;
            TreeItemXMLInfoClass _treeitemxmlInfo;
            RepoItemInfo _instance10796Info;
            JohnAugustineInfoClass _johnaugustineInfo;

            /// <summary>
            /// Creates a new ExactEquity  folder.
            /// </summary>
            public ExactEquityAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExactEquity", "/dom[@caption='ExactEquity' and @page='app.php' and @path='/site/app.php' and @browsername='Mozilla']", parentFolder, 30000, null, false, "fc1b5049-d13c-46b7-8c1d-f37a10def147", "")
            {
                _flex = new NewRepositoryFolders.FlexFolder(this);
                _treeitemxmlInfo = new TreeItemXMLInfoClass(this);
                _instance10796Info = new RepoItemInfo(this, "Instance10796", "dom[@domain='qa.nasdaqprivatemarket.com' and @caption='ExactEquity' and @page='app.php']//div[#'flash']/flexobject[@id='flex' and @caption='flex' and @movie='https://exact-equity-swfs.s3-us-west-2.amazonaws.com/swfs/f6a8f4ef407221388f295dd9927362fc834dca2d.swf?v=135']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='maintable' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@id='mainArea' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@type='Canvas' and @fulltype='mx.containers::Canvas']/container[@id='boxMainArea' and @type='HBox' and @fulltype='mx.containers::HBox']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='_main_HGroup2' and @displayname='_main_HGroup2' and @type='HGroup']/container[@id='captableBox' and @displayname='captable132' and @type='Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@id='tabnavigator' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@id='awardsView' and @caption='activetab' and @type='NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/container[@id='optionPlanViewStack' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@caption='activetab' and @type='NavigatorContent' and @fulltype='spark.components::NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/table[@id='optionsDataGrid' and @type='DataGrid' and @fulltype='spark.components::DataGrid']/row[@index='0' and @dataitemtype='com.exactequity.vos::GrantVO']/cell[@text='John Augustine' and @columnindex='2' and @rowindex='0']/text[@type='TextLine' and @fulltype='flash.text.engine::TextLine']", 30000, null, "6b9b97e5-fc50-4966-870e-494cc4c86299");
                _johnaugustineInfo = new JohnAugustineInfoClass(this);
            }

            /// <summary>
            /// The TreeItemXMLInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("032a98cc-0988-4a28-b36d-fe6108ba30de")]
            public class TreeItemXMLInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TreeItemXMLInfoClass class constructor.
                /// </summary>
                public TreeItemXMLInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TreeItemXML", ".//div[#'flash']/flexobject[@id='flex']/?/?/container[@type='HBox']//container[@id='_main_HGroup2']/container[3]/container[@id='navigationTree']//container[@id='_NavigationTree_Group4']/tree[@automationname='sidebarNavigation']/treeitem[@text='Grants']/treeitem", 30000, null, "032a98cc-0988-4a28-b36d-fe6108ba30de")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("2907824f-08cb-40f6-9b4e-48ccb3cb27bf")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("2907824f-08cb-40f6-9b4e-48ccb3cb27bf");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2907824f-08cb-40f6-9b4e-48ccb3cb27bf")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2907824f-08cb-40f6-9b4e-48ccb3cb27bf", cropRect);
                }
            }

            /// <summary>
            /// The JohnAugustineInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("fef2d04f-5b3d-404f-956e-c1455ee4eabd")]
            public class JohnAugustineInfoClass : RepoItemInfo
            {
                /// <summary>
                /// JohnAugustineInfoClass class constructor.
                /// </summary>
                public JohnAugustineInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "JohnAugustine", ".//div[#'flash']/flexobject[@id='flex' and @caption='flex' and @movie='https://exact-equity-swfs.s3-us-west-2.amazonaws.com/swfs/f6a8f4ef407221388f295dd9927362fc834dca2d.swf?v=135']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='maintable' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@id='mainArea' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@type='Canvas' and @fulltype='mx.containers::Canvas']/container[@id='boxMainArea' and @type='HBox' and @fulltype='mx.containers::HBox']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='_main_HGroup2' and @displayname='_main_HGroup2' and @type='HGroup']/container[@id='captableBox' and @displayname='captable132' and @type='Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@id='tabnavigator' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@id='awardsView' and @caption='activetab' and @type='NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/container[@id='optionPlanViewStack' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@caption='activetab' and @type='NavigatorContent' and @fulltype='spark.components::NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/table[@id='optionsDataGrid' and @type='DataGrid' and @fulltype='spark.components::DataGrid']/row[@index='0' and @dataitemtype='com.exactequity.vos::GrantVO']/cell[@text='John Augustine' and @columnindex='2' and @rowindex='0']", 30000, null, "fef2d04f-5b3d-404f-956e-c1455ee4eabd")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("7914c714-40c0-4de2-bada-99f87aa4257e")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("7914c714-40c0-4de2-bada-99f87aa4257e");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7914c714-40c0-4de2-bada-99f87aa4257e")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7914c714-40c0-4de2-bada-99f87aa4257e", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("88201f94-6aa6-4af1-b19e-d1be0f3d31fe")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("88201f94-6aa6-4af1-b19e-d1be0f3d31fe");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("88201f94-6aa6-4af1-b19e-d1be0f3d31fe")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("88201f94-6aa6-4af1-b19e-d1be0f3d31fe", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fc1b5049-d13c-46b7-8c1d-f37a10def147")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc1b5049-d13c-46b7-8c1d-f37a10def147")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TreeItemXML item.
            /// </summary>
            [RepositoryItem("032a98cc-0988-4a28-b36d-fe6108ba30de")]
            public virtual Ranorex.TreeItem TreeItemXML
            {
                get
                {
                    return _treeitemxmlInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TreeItemXML item info.
            /// </summary>
            [RepositoryItemInfo("032a98cc-0988-4a28-b36d-fe6108ba30de")]
            public virtual TreeItemXMLInfoClass TreeItemXMLInfo
            {
                get
                {
                    return _treeitemxmlInfo;
                }
            }

            /// <summary>
            /// The Instance10796 item.
            /// </summary>
            [RepositoryItem("6b9b97e5-fc50-4966-870e-494cc4c86299")]
            public virtual Ranorex.Text Instance10796
            {
                get
                {
                    return _instance10796Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Instance10796 item info.
            /// </summary>
            [RepositoryItemInfo("6b9b97e5-fc50-4966-870e-494cc4c86299")]
            public virtual RepoItemInfo Instance10796Info
            {
                get
                {
                    return _instance10796Info;
                }
            }

            /// <summary>
            /// The JohnAugustine item.
            /// </summary>
            [RepositoryItem("fef2d04f-5b3d-404f-956e-c1455ee4eabd")]
            public virtual Ranorex.Cell JohnAugustine
            {
                get
                {
                    return _johnaugustineInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The JohnAugustine item info.
            /// </summary>
            [RepositoryItemInfo("fef2d04f-5b3d-404f-956e-c1455ee4eabd")]
            public virtual JohnAugustineInfoClass JohnAugustineInfo
            {
                get
                {
                    return _johnaugustineInfo;
                }
            }

            /// <summary>
            /// The Flex folder.
            /// </summary>
            [RepositoryFolder("4d026df1-ce5b-49ae-9719-b5c4bc2e3aa1")]
            public virtual NewRepositoryFolders.FlexFolder Flex
            {
                get { return _flex; }
            }
        }

        /// <summary>
        /// The FlexFolder folder.
        /// </summary>
        [RepositoryFolder("4d026df1-ce5b-49ae-9719-b5c4bc2e3aa1")]
        public partial class FlexFolder : RepoGenBaseFolder
        {
            JohnAugustine1InfoClass _johnaugustine1Info;
            RepoItemInfo _participantsInfo;
            RepoItemInfo _closebuttonInfo;
            RepoItemInfo _terminationInfo;
            RepoItemInfo _instance14880Info;
            RepoItemInfo _thumbInfo;
            RepoItemInfo _cell25apr2016Info;

            /// <summary>
            /// Creates a new Flex  folder.
            /// </summary>
            public FlexFolder(RepoGenBaseFolder parentFolder) :
                    base("Flex", ".//div[#'flash']/flexobject[@id='flex' and @caption='flex' and @movie='https://exact-equity-swfs.s3-us-west-2.amazonaws.com/swfs/f6a8f4ef407221388f295dd9927362fc834dca2d.swf?v=135']", parentFolder, 30000, null, false, "4d026df1-ce5b-49ae-9719-b5c4bc2e3aa1", "")
            {
                _johnaugustine1Info = new JohnAugustine1InfoClass(this);
                _participantsInfo = new RepoItemInfo(this, "Participants", "container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='maintable' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@id='mainArea' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@type='Canvas' and @fulltype='mx.containers::Canvas']/container[@id='boxMainArea' and @type='HBox' and @fulltype='mx.containers::HBox']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='_main_HGroup2' and @displayname='_main_HGroup2' and @type='HGroup']/container[@type='Group' and @fulltype='spark.components::Group']/container[@id='navigationTree' and @displayname='NavigationTree122' and @type='Group']/container[@id='wrapper' and @type='Group' and @fulltype='spark.components::Group']/container[@type='Group' and @fulltype='spark.components::Group']/container[@id='_NavigationTree_Group4' and @type='Group' and @fulltype='spark.components::Group']/tree[@automationname='sidebarNavigation' and @id='navigationTree' and @type='Tree']/treeitem[@text='Participants' and @dataitemtype='XML']", 30000, null, "a0d5e0f3-0fa5-4042-a89b-0f82b6d6d2d2");
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", "element[@type='GrantEditor' and @fulltype='com.exactequity.popups::GrantEditor']/container[@type='Group' and @fulltype='spark.components::Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@id='topGroup' and @type='Group' and @fulltype='spark.components::Group']/button[@id='closeButton' and @type='Button' and @fulltype='spark.components::Button']", 30000, null, "a3e2fa17-8aea-4e26-b923-57a1eaab93e1");
                _terminationInfo = new RepoItemInfo(this, "Termination", "element[@type='ParticipantEditor' and @fulltype='com.exactequity.popups::ParticipantEditor']/container[@type='Group' and @fulltype='spark.components::Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@type='HGroup' and @fulltype='spark.components::HGroup']/toolbar[@id='_ParticipantEditor_ButtonBar1' and @type='ButtonBar' and @fulltype='spark.components::ButtonBar']/container[@id='dataGroup' and @type='DataGroup' and @fulltype='spark.components::DataGroup']/element[@type='EEButtonBarSkinInnerClass2' and @fulltype='com.exactequity.skins::EEButtonBarSkinInnerClass2']/element[@type='EEButtonBarButtonSkin' and @fulltype='com.exactequity.skins::EEButtonBarButtonSkin']/text[@id='labelDisplay' and @caption='Termination' and @type='Label']", 30000, null, "f8a3bcf3-d155-4cb6-97bf-d2ba55aae580");
                _instance14880Info = new RepoItemInfo(this, "Instance14880", "element[@type='ParticipantEditor' and @fulltype='com.exactequity.popups::ParticipantEditor']/container[@type='Group' and @fulltype='spark.components::Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@type='HGroup' and @fulltype='spark.components::HGroup']/container[@id='participantsEditorViewStack' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@id='_ParticipantEditor_TerminationTab1' and @caption='activetab' and @type='NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/table[@id='terminationDataGrid' and @type='DataGrid' and @fulltype='spark.components::DataGrid']/row[@index='1' and @dataitemtype='com.exactequity.vos::GrantVO']/cell[@text='25 Apr 2016' and @columnindex='9' and @rowindex='1']/text[@type='TextLine' and @fulltype='flash.text.engine::TextLine']", 30000, null, "21a4f2ae-8f6e-4117-85cc-a5a59213c03c");
                _thumbInfo = new RepoItemInfo(this, "Thumb", "container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='maintable' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@id='mainArea' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@type='Canvas' and @fulltype='mx.containers::Canvas']/container[@id='boxMainArea' and @type='HBox' and @fulltype='mx.containers::HBox']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='_main_HGroup2' and @displayname='_main_HGroup2' and @type='HGroup']/container[@type='Group' and @fulltype='spark.components::Group']/container[@id='navigationTree' and @displayname='NavigationTree122' and @type='Group']/container[@id='wrapper' and @type='Group' and @fulltype='spark.components::Group']/container[@type='Group' and @fulltype='spark.components::Group']/scrollbar[@id='navigationTreeScrollBar' and @type='VScrollBar' and @fulltype='spark.components::VScrollBar']/button[@id='thumb' and @type='Button' and @fulltype='spark.components::Button']", 30000, null, "3ce2e768-ca44-48c3-b4f1-1cde5f308132");
                _cell25apr2016Info = new RepoItemInfo(this, "Cell25Apr2016", "element[@type='ParticipantEditor' and @fulltype='com.exactequity.popups::ParticipantEditor']/container[@type='Group' and @fulltype='spark.components::Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@type='HGroup' and @fulltype='spark.components::HGroup']/container[@id='participantsEditorViewStack' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@id='_ParticipantEditor_TerminationTab1' and @caption='activetab' and @type='NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/table[@id='terminationDataGrid' and @type='DataGrid' and @fulltype='spark.components::DataGrid']/column[@text='Final Date To Exercise' and @index='9']/cell[@text='25 Apr 2016' and @columnindex='9' and @rowindex='1']", 30000, null, "d423b87e-1caa-43b0-9a74-6354ad72d3d1");
            }

            /// <summary>
            /// The JohnAugustine1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("4d9660cc-33c2-4348-b38e-0c94c2c9b08a")]
            public class JohnAugustine1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// JohnAugustine1InfoClass class constructor.
                /// </summary>
                public JohnAugustine1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "JohnAugustine1", "container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='maintable' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@id='mainArea' and @type='VBox' and @fulltype='mx.containers::VBox']/container[@type='Canvas' and @fulltype='mx.containers::Canvas']/container[@id='boxMainArea' and @type='HBox' and @fulltype='mx.containers::HBox']/container[@type='VBox' and @fulltype='mx.containers::VBox']/container[@type='HBox' and @fulltype='mx.containers::HBox']/container[@id='_main_HGroup2' and @displayname='_main_HGroup2' and @type='HGroup']/container[@id='captableBox' and @displayname='captable132' and @type='Group']/container[@type='VGroup' and @fulltype='spark.components::VGroup']/container[@id='tabnavigator' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@id='holdersView' and @caption='activetab' and @type='NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/container[@id='participantViewStack' and @type='ViewStack' and @fulltype='mx.containers::ViewStack']/container[@caption='activetab' and @type='NavigatorContent' and @fulltype='spark.components::NavigatorContent']/container[@type='Scroller' and @fulltype='spark.components::Scroller']/table[@id='participantsDataGrid' and @type='DataGrid' and @fulltype='spark.components::DataGrid']/row[@index='2' and @dataitemtype='com.exactequity.vos::ParticipantViewModelVO']/cell[@text='John Augustine' and @columnindex='0' and @rowindex='2']", 30000, null, "4d9660cc-33c2-4348-b38e-0c94c2c9b08a")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("58b7f33d-ae32-4249-9d90-6b735e993c0c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("58b7f33d-ae32-4249-9d90-6b735e993c0c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("58b7f33d-ae32-4249-9d90-6b735e993c0c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("58b7f33d-ae32-4249-9d90-6b735e993c0c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("96f16f9f-34a9-4d09-9060-7b29b300fca8")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("96f16f9f-34a9-4d09-9060-7b29b300fca8");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("96f16f9f-34a9-4d09-9060-7b29b300fca8")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("96f16f9f-34a9-4d09-9060-7b29b300fca8", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d026df1-ce5b-49ae-9719-b5c4bc2e3aa1")]
            public virtual Ranorex.FlexObject Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.FlexObject>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d026df1-ce5b-49ae-9719-b5c4bc2e3aa1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JohnAugustine1 item.
            /// </summary>
            [RepositoryItem("4d9660cc-33c2-4348-b38e-0c94c2c9b08a")]
            public virtual Ranorex.Cell JohnAugustine1
            {
                get
                {
                    return _johnaugustine1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The JohnAugustine1 item info.
            /// </summary>
            [RepositoryItemInfo("4d9660cc-33c2-4348-b38e-0c94c2c9b08a")]
            public virtual JohnAugustine1InfoClass JohnAugustine1Info
            {
                get
                {
                    return _johnaugustine1Info;
                }
            }

            /// <summary>
            /// The Participants item.
            /// </summary>
            [RepositoryItem("a0d5e0f3-0fa5-4042-a89b-0f82b6d6d2d2")]
            public virtual Ranorex.TreeItem Participants
            {
                get
                {
                    return _participantsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Participants item info.
            /// </summary>
            [RepositoryItemInfo("a0d5e0f3-0fa5-4042-a89b-0f82b6d6d2d2")]
            public virtual RepoItemInfo ParticipantsInfo
            {
                get
                {
                    return _participantsInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("a3e2fa17-8aea-4e26-b923-57a1eaab93e1")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("a3e2fa17-8aea-4e26-b923-57a1eaab93e1")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }

            /// <summary>
            /// The Termination item.
            /// </summary>
            [RepositoryItem("f8a3bcf3-d155-4cb6-97bf-d2ba55aae580")]
            public virtual Ranorex.Text Termination
            {
                get
                {
                    return _terminationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Termination item info.
            /// </summary>
            [RepositoryItemInfo("f8a3bcf3-d155-4cb6-97bf-d2ba55aae580")]
            public virtual RepoItemInfo TerminationInfo
            {
                get
                {
                    return _terminationInfo;
                }
            }

            /// <summary>
            /// The Instance14880 item.
            /// </summary>
            [RepositoryItem("21a4f2ae-8f6e-4117-85cc-a5a59213c03c")]
            public virtual Ranorex.Text Instance14880
            {
                get
                {
                    return _instance14880Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Instance14880 item info.
            /// </summary>
            [RepositoryItemInfo("21a4f2ae-8f6e-4117-85cc-a5a59213c03c")]
            public virtual RepoItemInfo Instance14880Info
            {
                get
                {
                    return _instance14880Info;
                }
            }

            /// <summary>
            /// The Thumb item.
            /// </summary>
            [RepositoryItem("3ce2e768-ca44-48c3-b4f1-1cde5f308132")]
            public virtual Ranorex.Button Thumb
            {
                get
                {
                    return _thumbInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Thumb item info.
            /// </summary>
            [RepositoryItemInfo("3ce2e768-ca44-48c3-b4f1-1cde5f308132")]
            public virtual RepoItemInfo ThumbInfo
            {
                get
                {
                    return _thumbInfo;
                }
            }

            /// <summary>
            /// The Cell25Apr2016 item.
            /// </summary>
            [RepositoryItem("d423b87e-1caa-43b0-9a74-6354ad72d3d1")]
            public virtual Ranorex.Cell Cell25Apr2016
            {
                get
                {
                    return _cell25apr2016Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell25Apr2016 item info.
            /// </summary>
            [RepositoryItemInfo("d423b87e-1caa-43b0-9a74-6354ad72d3d1")]
            public virtual RepoItemInfo Cell25Apr2016Info
            {
                get
                {
                    return _cell25apr2016Info;
                }
            }
        }

        /// <summary>
        /// The FileCNQExactEquityFlexClientCAppFolder folder.
        /// </summary>
        [RepositoryFolder("525214a1-bbb3-4596-aa54-8169c8628f32")]
        public partial class FileCNQExactEquityFlexClientCAppFolder : RepoGenBaseFolder
        {
            OptionPlan2011Aug11InfoClass _optionplan2011aug11Info;

            /// <summary>
            /// Creates a new FileCNQExactEquityFlexClientC  folder.
            /// </summary>
            public FileCNQExactEquityFlexClientCAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileCNQExactEquityFlexClientC", "/dom[@caption~'^file:///C:/NQ/exact_equit']", parentFolder, 30000, null, false, "525214a1-bbb3-4596-aa54-8169c8628f32", "")
            {
                _optionplan2011aug11Info = new OptionPlan2011Aug11InfoClass(this);
            }

            /// <summary>
            /// The OptionPlan2011Aug11InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("ed2644e5-3d0b-4f6a-a47b-1134909ec715")]
            public class OptionPlan2011Aug11InfoClass : RepoItemInfo
            {
                /// <summary>
                /// OptionPlan2011Aug11InfoClass class constructor.
                /// </summary>
                public OptionPlan2011Aug11InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "OptionPlan2011Aug11", ".//object[#'main']/?/?/tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename='Option Plan 2011 (Aug 11)']", 30000, null, "ed2644e5-3d0b-4f6a-a47b-1134909ec715")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e87b9711-6d9c-4014-ac0a-96ed98316302")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e87b9711-6d9c-4014-ac0a-96ed98316302");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e87b9711-6d9c-4014-ac0a-96ed98316302")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e87b9711-6d9c-4014-ac0a-96ed98316302", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("525214a1-bbb3-4596-aa54-8169c8628f32")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("525214a1-bbb3-4596-aa54-8169c8628f32")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug11 item.
            /// </summary>
            [RepositoryItem("ed2644e5-3d0b-4f6a-a47b-1134909ec715")]
            public virtual Ranorex.TreeItem OptionPlan2011Aug11
            {
                get
                {
                    return _optionplan2011aug11Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug11 item info.
            /// </summary>
            [RepositoryItemInfo("ed2644e5-3d0b-4f6a-a47b-1134909ec715")]
            public virtual OptionPlan2011Aug11InfoClass OptionPlan2011Aug11Info
            {
                get
                {
                    return _optionplan2011aug11Info;
                }
            }
        }

        /// <summary>
        /// The ExactEquity1AppFolder folder.
        /// </summary>
        [RepositoryFolder("cf552641-354c-4658-ab2c-145d09c35e82")]
        public partial class ExactEquity1AppFolder : RepoGenBaseFolder
        {
            NewRepositoryFolders.ContainerMainHGroup2Folder _containermainhgroup2;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _copyrightInfo;
            RepoItemInfo _spantagvarflashvarseqbaseurleqqaInfo;
            GraphicInfoClass _graphicInfo;
            RepoItemInfo _textinputInfo;
            FlexInfoClass _flexInfo;

            /// <summary>
            /// Creates a new ExactEquity1  folder.
            /// </summary>
            public ExactEquity1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExactEquity1", "/dom[1]", parentFolder, 30000, null, false, "cf552641-354c-4658-ab2c-145d09c35e82", "")
            {
                _containermainhgroup2 = new NewRepositoryFolders.ContainerMainHGroup2Folder(this);
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'Email']", 30000, null, "6a5a0147-665a-4338-8ad4-c6d2f1bce0db");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", 30000, null, "15cc835f-4723-40f9-8364-8798e6b8825e");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//form[#'loginForm']/?/?/button[@innertext='Log in']", 30000, null, "b343af58-a642-4ae2-8c92-bf84dd7c1c24");
                _copyrightInfo = new RepoItemInfo(this, "Copyright", ".//div[#'copyright']", 30000, null, "e50a1a9d-683d-4b7e-ac9c-dfda52ede2cd");
                _spantagvarflashvarseqbaseurleqqaInfo = new RepoItemInfo(this, "SpanTagVarFlashVarsEqBaseurlEqqa", "dom[@caption~'^https://qa\\.nasdaqprivatem']/descendant-or-self::*/pre[#'line1']/span[@innertext~'^\\ \\ \\ \\ var\\ flashVars\\ =\\ \"base']", 30000, null, "df7d513a-3759-4e0e-ad82-31d918995947");
                _graphicInfo = new GraphicInfoClass(this);
                _textinputInfo = new RepoItemInfo(this, "TextInput", ".//div[#'flash']/flexobject[@id='flex']//container[@id='container']//container[@type='HGroup']/container[@id='tabDetails']/container[@id='vboxGrant']//container[@id='boxBoard']/container[@id='boxException']/?/?/text[@type='TextInput']", 30000, null, "ef0695c4-4619-4c13-9c7c-9b429c4f997b");
                _flexInfo = new FlexInfoClass(this);
            }

            /// <summary>
            /// The GraphicInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("c512a133-7d3b-44da-9947-fc4654d5f934")]
            public class GraphicInfoClass : RepoItemInfo
            {
                /// <summary>
                /// GraphicInfoClass class constructor.
                /// </summary>
                public GraphicInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Graphic", ".//object[#'main']/element[@class='GeckoPluginWindow']/picture[6]", 30000, null, "c512a133-7d3b-44da-9947-fc4654d5f934")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("be830dae-a773-4708-885f-b634f0d0737d")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("be830dae-a773-4708-885f-b634f0d0737d");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("be830dae-a773-4708-885f-b634f0d0737d")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("be830dae-a773-4708-885f-b634f0d0737d", cropRect);
                }
            }

            /// <summary>
            /// The FlexInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("16dfc858-f51a-4e82-9e77-8693a490ed4d")]
            public class FlexInfoClass : RepoItemInfo
            {
                /// <summary>
                /// FlexInfoClass class constructor.
                /// </summary>
                public FlexInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Flex", "dom[@caption~'^file:///C:/NQ/exact_equit']//object[#'main']/?/?/tree[@accessiblerole='Outline']/?/?/treeitem[1]", 30000, null, "16dfc858-f51a-4e82-9e77-8693a490ed4d")
                { }

                /// <summary>
                /// Gets the OptionPlan2011Aug11_Screenshot1 item image.
                /// </summary>
                /// <returns>The OptionPlan2011Aug11_Screenshot1 image.</returns>
                [RepositoryImage("607ad38e-7b4e-41d1-ad80-4c30a98a48ab")]
                public CompressedImage GetOptionPlan2011Aug11_Screenshot1()
                {
                    return GetImage("607ad38e-7b4e-41d1-ad80-4c30a98a48ab");
                }

                /// <summary>
                /// Gets the OptionPlan2011Aug11_Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("607ad38e-7b4e-41d1-ad80-4c30a98a48ab")]
                public CompressedImage GetOptionPlan2011Aug11_Screenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("607ad38e-7b4e-41d1-ad80-4c30a98a48ab", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf552641-354c-4658-ab2c-145d09c35e82")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf552641-354c-4658-ab2c-145d09c35e82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("6a5a0147-665a-4338-8ad4-c6d2f1bce0db")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("6a5a0147-665a-4338-8ad4-c6d2f1bce0db")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("15cc835f-4723-40f9-8364-8798e6b8825e")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("15cc835f-4723-40f9-8364-8798e6b8825e")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("b343af58-a642-4ae2-8c92-bf84dd7c1c24")]
            public virtual Ranorex.ButtonTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("b343af58-a642-4ae2-8c92-bf84dd7c1c24")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Copyright item.
            /// </summary>
            [RepositoryItem("e50a1a9d-683d-4b7e-ac9c-dfda52ede2cd")]
            public virtual Ranorex.DivTag Copyright
            {
                get
                {
                    return _copyrightInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Copyright item info.
            /// </summary>
            [RepositoryItemInfo("e50a1a9d-683d-4b7e-ac9c-dfda52ede2cd")]
            public virtual RepoItemInfo CopyrightInfo
            {
                get
                {
                    return _copyrightInfo;
                }
            }

            /// <summary>
            /// The SpanTagVarFlashVarsEqBaseurlEqqa item.
            /// </summary>
            [RepositoryItem("df7d513a-3759-4e0e-ad82-31d918995947")]
            public virtual Ranorex.SpanTag SpanTagVarFlashVarsEqBaseurlEqqa
            {
                get
                {
                    return _spantagvarflashvarseqbaseurleqqaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagVarFlashVarsEqBaseurlEqqa item info.
            /// </summary>
            [RepositoryItemInfo("df7d513a-3759-4e0e-ad82-31d918995947")]
            public virtual RepoItemInfo SpanTagVarFlashVarsEqBaseurlEqqaInfo
            {
                get
                {
                    return _spantagvarflashvarseqbaseurleqqaInfo;
                }
            }

            /// <summary>
            /// The Graphic item.
            /// </summary>
            [RepositoryItem("c512a133-7d3b-44da-9947-fc4654d5f934")]
            public virtual Ranorex.Picture Graphic
            {
                get
                {
                    return _graphicInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic item info.
            /// </summary>
            [RepositoryItemInfo("c512a133-7d3b-44da-9947-fc4654d5f934")]
            public virtual GraphicInfoClass GraphicInfo
            {
                get
                {
                    return _graphicInfo;
                }
            }

            /// <summary>
            /// The TextInput item.
            /// </summary>
            [RepositoryItem("ef0695c4-4619-4c13-9c7c-9b429c4f997b")]
            public virtual Ranorex.Text TextInput
            {
                get
                {
                    return _textinputInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextInput item info.
            /// </summary>
            [RepositoryItemInfo("ef0695c4-4619-4c13-9c7c-9b429c4f997b")]
            public virtual RepoItemInfo TextInputInfo
            {
                get
                {
                    return _textinputInfo;
                }
            }

            /// <summary>
            /// The Flex item.
            /// </summary>
            [RepositoryItem("16dfc858-f51a-4e82-9e77-8693a490ed4d")]
            public virtual Ranorex.TreeItem Flex
            {
                get
                {
                    return _flexInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Flex item info.
            /// </summary>
            [RepositoryItemInfo("16dfc858-f51a-4e82-9e77-8693a490ed4d")]
            public virtual FlexInfoClass FlexInfo
            {
                get
                {
                    return _flexInfo;
                }
            }

            /// <summary>
            /// The ContainerMainHGroup2 folder.
            /// </summary>
            [RepositoryFolder("56445c66-19ba-46a3-aa4e-5f82cbb0a9c8")]
            public virtual NewRepositoryFolders.ContainerMainHGroup2Folder ContainerMainHGroup2
            {
                get { return _containermainhgroup2; }
            }
        }

        /// <summary>
        /// The ContainerMainHGroup2Folder folder.
        /// </summary>
        [RepositoryFolder("56445c66-19ba-46a3-aa4e-5f82cbb0a9c8")]
        public partial class ContainerMainHGroup2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _grants1Info;
            OptionPlan2011Aug112InfoClass _optionplan2011aug112Info;
            RepoItemInfo _options1Info;
            RepoItemInfo _textlineInfo;

            /// <summary>
            /// Creates a new ContainerMainHGroup2  folder.
            /// </summary>
            public ContainerMainHGroup2Folder(RepoGenBaseFolder parentFolder) :
                    base("ContainerMainHGroup2", ".//div[#'flash']/flexobject[@id='flex']/?/?/container[@type='HBox']//container[@id='_main_HGroup2']", parentFolder, 30000, null, false, "56445c66-19ba-46a3-aa4e-5f82cbb0a9c8", "")
            {
                _grants1Info = new RepoItemInfo(this, "Grants1", "container[3]/container[@id='navigationTree']//container[@id='_NavigationTree_Group4']/tree[@automationname='sidebarNavigation']/treeitem[@text='Grants']", 30000, null, "7ee62997-2ef1-40e1-b1fd-0f635645d227");
                _optionplan2011aug112Info = new OptionPlan2011Aug112InfoClass(this);
                _options1Info = new RepoItemInfo(this, "Options1", "container[@id='captableBox']/?/?/container[@id='tabnavigator']/container[@id='awardsView']/?/?/element[@id='tabBar']/container[@id='dataGroup']/?/?/text[@caption='Options']", 30000, null, "cb78a8f2-b20b-48d0-b41c-4a8b8463a220");
                _textlineInfo = new RepoItemInfo(this, "TextLine", "container[@id='captableBox']//container[@id='awardsView']/?/?/container[@id='optionPlanViewStack']/container[@caption='activetab']/?/?/table[@id='optionsDataGrid']/row[@index='1']/cell[@text='Jane Corsow']/text[@type='TextLine']", 30000, null, "2f045572-110d-4d57-8fb9-1579160baae0");
            }

            /// <summary>
            /// The OptionPlan2011Aug112InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("afbd345c-52eb-4907-a68c-b0c66d9d4cf9")]
            public class OptionPlan2011Aug112InfoClass : RepoItemInfo
            {
                /// <summary>
                /// OptionPlan2011Aug112InfoClass class constructor.
                /// </summary>
                public OptionPlan2011Aug112InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "OptionPlan2011Aug112", "dom[@caption='file:///C:/NQ/exact_equity_flex_client/client/bin-debug/main.html' and @page='main.html' and @path='C:/NQ/exact_equity_flex_client/client/bin-debug/main.html']//object[#'main']/element[@class='GeckoPluginWindow' and @instance='0']/tree[@accessiblerole='Outline']/treeitem[@accessiblename='Grants' and @accessiblerole='OutlineItem' and @text='Grants']/treeitem[@accessiblename='Option Plan 2011 (Aug 11)' and @accessiblerole='OutlineItem' and @text='Option Plan 2011 (Aug 11)']", 30000, null, "afbd345c-52eb-4907-a68c-b0c66d9d4cf9")
                { }

                /// <summary>
                /// Gets the OptionPlan2011Aug11_Screenshot1 item image.
                /// </summary>
                /// <returns>The OptionPlan2011Aug11_Screenshot1 image.</returns>
                [RepositoryImage("3cebffe2-1cbc-47a4-81e4-e196a81fc088")]
                public CompressedImage GetOptionPlan2011Aug11_Screenshot1()
                {
                    return GetImage("3cebffe2-1cbc-47a4-81e4-e196a81fc088");
                }

                /// <summary>
                /// Gets the OptionPlan2011Aug11_Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3cebffe2-1cbc-47a4-81e4-e196a81fc088")]
                public CompressedImage GetOptionPlan2011Aug11_Screenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3cebffe2-1cbc-47a4-81e4-e196a81fc088", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("56445c66-19ba-46a3-aa4e-5f82cbb0a9c8")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("56445c66-19ba-46a3-aa4e-5f82cbb0a9c8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Grants1 item.
            /// </summary>
            [RepositoryItem("7ee62997-2ef1-40e1-b1fd-0f635645d227")]
            public virtual Ranorex.TreeItem Grants1
            {
                get
                {
                    return _grants1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Grants1 item info.
            /// </summary>
            [RepositoryItemInfo("7ee62997-2ef1-40e1-b1fd-0f635645d227")]
            public virtual RepoItemInfo Grants1Info
            {
                get
                {
                    return _grants1Info;
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug112 item.
            /// </summary>
            [RepositoryItem("afbd345c-52eb-4907-a68c-b0c66d9d4cf9")]
            public virtual Ranorex.TreeItem OptionPlan2011Aug112
            {
                get
                {
                    return _optionplan2011aug112Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug112 item info.
            /// </summary>
            [RepositoryItemInfo("afbd345c-52eb-4907-a68c-b0c66d9d4cf9")]
            public virtual OptionPlan2011Aug112InfoClass OptionPlan2011Aug112Info
            {
                get
                {
                    return _optionplan2011aug112Info;
                }
            }

            /// <summary>
            /// The Options1 item.
            /// </summary>
            [RepositoryItem("cb78a8f2-b20b-48d0-b41c-4a8b8463a220")]
            public virtual Ranorex.Text Options1
            {
                get
                {
                    return _options1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Options1 item info.
            /// </summary>
            [RepositoryItemInfo("cb78a8f2-b20b-48d0-b41c-4a8b8463a220")]
            public virtual RepoItemInfo Options1Info
            {
                get
                {
                    return _options1Info;
                }
            }

            /// <summary>
            /// The TextLine item.
            /// </summary>
            [RepositoryItem("2f045572-110d-4d57-8fb9-1579160baae0")]
            public virtual Ranorex.Text TextLine
            {
                get
                {
                    return _textlineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextLine item info.
            /// </summary>
            [RepositoryItemInfo("2f045572-110d-4d57-8fb9-1579160baae0")]
            public virtual RepoItemInfo TextLineInfo
            {
                get
                {
                    return _textlineInfo;
                }
            }
        }

        /// <summary>
        /// The FirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("0b805b63-c5af-49c9-96b0-876b404025ee")]
        public partial class FirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viewpagesourceInfo;
            RepoItemInfo _copyInfo;

            /// <summary>
            /// Creates a new Firefox  folder.
            /// </summary>
            public FirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Firefox", "/contextmenu[@processname='firefox']", parentFolder, 30000, null, true, "0b805b63-c5af-49c9-96b0-876b404025ee", "")
            {
                _viewpagesourceInfo = new RepoItemInfo(this, "ViewPageSource", "?/?/menuitem[@accessiblename='View Page Source']", 30000, null, "de79c7e6-f309-4620-98df-fb2f67a4ef4a");
                _copyInfo = new RepoItemInfo(this, "Copy", "?/?/menuitem[@accessiblename='Copy']", 30000, null, "4795bb76-54f5-4d95-a205-2330abdc8790");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b805b63-c5af-49c9-96b0-876b404025ee")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b805b63-c5af-49c9-96b0-876b404025ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewPageSource item.
            /// </summary>
            [RepositoryItem("de79c7e6-f309-4620-98df-fb2f67a4ef4a")]
            public virtual Ranorex.MenuItem ViewPageSource
            {
                get
                {
                    return _viewpagesourceInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ViewPageSource item info.
            /// </summary>
            [RepositoryItemInfo("de79c7e6-f309-4620-98df-fb2f67a4ef4a")]
            public virtual RepoItemInfo ViewPageSourceInfo
            {
                get
                {
                    return _viewpagesourceInfo;
                }
            }

            /// <summary>
            /// The Copy item.
            /// </summary>
            [RepositoryItem("4795bb76-54f5-4d95-a205-2330abdc8790")]
            public virtual Ranorex.MenuItem Copy
            {
                get
                {
                    return _copyInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Copy item info.
            /// </summary>
            [RepositoryItemInfo("4795bb76-54f5-4d95-a205-2330abdc8790")]
            public virtual RepoItemInfo CopyInfo
            {
                get
                {
                    return _copyInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("6c173280-751c-44a1-903f-a0729adbf55b")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _flashnpmbindebugmainhtmlflashInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "6c173280-751c-44a1-903f-a0729adbf55b", "")
            {
                _flashnpmbindebugmainhtmlflashInfo = new RepoItemInfo(this, "FlashNPMBinDebugMainHtmlFlash", "?/?/container[@caption='Running applications']/?/?/toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Flash\\ -\\ NPM/bin-debug/mai']", 30000, null, "188b860f-b014-486b-b161-d1a24a03fe14");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "a49d44e8-77d5-43ef-9fdf-2be95e4cdaa8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6c173280-751c-44a1-903f-a0729adbf55b")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6c173280-751c-44a1-903f-a0729adbf55b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FlashNPMBinDebugMainHtmlFlash item.
            /// </summary>
            [RepositoryItem("188b860f-b014-486b-b161-d1a24a03fe14")]
            public virtual Ranorex.Button FlashNPMBinDebugMainHtmlFlash
            {
                get
                {
                    return _flashnpmbindebugmainhtmlflashInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FlashNPMBinDebugMainHtmlFlash item info.
            /// </summary>
            [RepositoryItemInfo("188b860f-b014-486b-b161-d1a24a03fe14")]
            public virtual RepoItemInfo FlashNPMBinDebugMainHtmlFlashInfo
            {
                get
                {
                    return _flashnpmbindebugmainhtmlflashInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("a49d44e8-77d5-43ef-9fdf-2be95e4cdaa8")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("a49d44e8-77d5-43ef-9fdf-2be95e4cdaa8")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The FlashNPMBinDebugMainHtmlFlashAppFolder folder.
        /// </summary>
        [RepositoryFolder("259f752b-09dc-4fc8-8965-8d53ebca8fae")]
        public partial class FlashNPMBinDebugMainHtmlFlashAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mainhtmlInfo;
            RepoItemInfo _styledtextInfo;

            /// <summary>
            /// Creates a new FlashNPMBinDebugMainHtmlFlash  folder.
            /// </summary>
            public FlashNPMBinDebugMainHtmlFlashAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FlashNPMBinDebugMainHtmlFlash", "/form[@title~'^Flash\\ -\\ NPM/bin-debug/mai']", parentFolder, 30000, null, false, "259f752b-09dc-4fc8-8965-8d53ebca8fae", "")
            {
                _mainhtmlInfo = new RepoItemInfo(this, "MainHtml", "container[@type='Composite']/container/container[5]/?/?/tabpage[@title='main.html']", 30000, null, "330b919a-29a2-4cc7-918c-54eff79e5200");
                _styledtextInfo = new RepoItemInfo(this, "StyledText", "container[@type='Composite']/container/container[5]/container[@type='Composite']/container/container[@type='Composite']/container[@type='Composite']/?/?/text[@type='StyledText']", 30000, null, "e85c11fe-b3b4-4e57-b440-d25b64e5ab95");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("259f752b-09dc-4fc8-8965-8d53ebca8fae")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("259f752b-09dc-4fc8-8965-8d53ebca8fae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainHtml item.
            /// </summary>
            [RepositoryItem("330b919a-29a2-4cc7-918c-54eff79e5200")]
            public virtual Ranorex.TabPage MainHtml
            {
                get
                {
                    return _mainhtmlInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MainHtml item info.
            /// </summary>
            [RepositoryItemInfo("330b919a-29a2-4cc7-918c-54eff79e5200")]
            public virtual RepoItemInfo MainHtmlInfo
            {
                get
                {
                    return _mainhtmlInfo;
                }
            }

            /// <summary>
            /// The StyledText item.
            /// </summary>
            [RepositoryItem("e85c11fe-b3b4-4e57-b440-d25b64e5ab95")]
            public virtual Ranorex.Text StyledText
            {
                get
                {
                    return _styledtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StyledText item info.
            /// </summary>
            [RepositoryItemInfo("e85c11fe-b3b4-4e57-b440-d25b64e5ab95")]
            public virtual RepoItemInfo StyledTextInfo
            {
                get
                {
                    return _styledtextInfo;
                }
            }
        }

        /// <summary>
        /// The ExactEquity2AppFolder folder.
        /// </summary>
        [RepositoryFolder("1cc404cd-ea2f-4df6-a540-a3d5aa1741fe")]
        public partial class ExactEquity2AppFolder : RepoGenBaseFolder
        {
            NewRepositoryFolders.ContainerMainHGroup2Folder1 _containermainhgroup2;

            /// <summary>
            /// Creates a new ExactEquity2  folder.
            /// </summary>
            public ExactEquity2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExactEquity2", "/dom[1]", parentFolder, 30000, null, false, "1cc404cd-ea2f-4df6-a540-a3d5aa1741fe", "")
            {
                _containermainhgroup2 = new NewRepositoryFolders.ContainerMainHGroup2Folder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1cc404cd-ea2f-4df6-a540-a3d5aa1741fe")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1cc404cd-ea2f-4df6-a540-a3d5aa1741fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerMainHGroup2 folder.
            /// </summary>
            [RepositoryFolder("f23c72ce-b5d0-4689-8013-25a8ede3fc20")]
            public virtual NewRepositoryFolders.ContainerMainHGroup2Folder1 ContainerMainHGroup2
            {
                get { return _containermainhgroup2; }
            }
        }

        /// <summary>
        /// The ContainerMainHGroup2Folder1 folder.
        /// </summary>
        [RepositoryFolder("f23c72ce-b5d0-4689-8013-25a8ede3fc20")]
        public partial class ContainerMainHGroup2Folder1 : RepoGenBaseFolder
        {
            RepoItemInfo _optionplan2011aug11Info;
            Scroller1InfoClass _scroller1Info;
            Copy_of_Scroller1InfoClass _copy_of_scroller1Info;

            /// <summary>
            /// Creates a new ContainerMainHGroup2  folder.
            /// </summary>
            public ContainerMainHGroup2Folder1(RepoGenBaseFolder parentFolder) :
                    base("ContainerMainHGroup2", ".//div[#'flash']/flexobject[@id='flex']/?/?/container[@type='HBox']//container[@id='_main_HGroup2']", parentFolder, 30000, null, false, "f23c72ce-b5d0-4689-8013-25a8ede3fc20", "")
            {
                _optionplan2011aug11Info = new RepoItemInfo(this, "OptionPlan2011Aug11", "container[3]/container[@id='navigationTree']//container[@id='_NavigationTree_Group4']/tree[@automationname='sidebarNavigation']/treeitem[@text='Grants']/treeitem[@text='Option Plan 2011 (Aug 11)']", 30000, null, "8cb21262-2505-4f11-bc9c-37b44d5df5ed");
                _scroller1Info = new Scroller1InfoClass(this);
                _copy_of_scroller1Info = new Copy_of_Scroller1InfoClass(this);
            }

            /// <summary>
            /// The Scroller1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("45f87eb2-451a-4b20-b821-ebdc685f345e")]
            public class Scroller1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// Scroller1InfoClass class constructor.
                /// </summary>
                public Scroller1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Scroller1", ".//object[#'main']/?/?/tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename='Option Plan 2011 (Aug 11)']", 30000, null, "45f87eb2-451a-4b20-b821-ebdc685f345e")
                { }

                /// <summary>
                /// Gets the OptionPlan2011Aug11_Screenshot1 item image.
                /// </summary>
                /// <returns>The OptionPlan2011Aug11_Screenshot1 image.</returns>
                [RepositoryImage("11dcada3-932a-4ff4-8e14-4b3d1687032c")]
                public CompressedImage GetOptionPlan2011Aug11_Screenshot1()
                {
                    return GetImage("11dcada3-932a-4ff4-8e14-4b3d1687032c");
                }

                /// <summary>
                /// Gets the OptionPlan2011Aug11_Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("11dcada3-932a-4ff4-8e14-4b3d1687032c")]
                public CompressedImage GetOptionPlan2011Aug11_Screenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("11dcada3-932a-4ff4-8e14-4b3d1687032c", cropRect);
                }
            }

            /// <summary>
            /// The Copy_of_Scroller1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("defb7b87-60ae-421d-a548-eb40b802e1da")]
            public class Copy_of_Scroller1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// Copy_of_Scroller1InfoClass class constructor.
                /// </summary>
                public Copy_of_Scroller1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Copy_of_Scroller1", ".//object[#'main']/?/?/tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename='Option Plan 2011 (Aug 11)']", 30000, null, "defb7b87-60ae-421d-a548-eb40b802e1da")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("008a45f7-f597-4450-9aab-1185f59c667b")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("008a45f7-f597-4450-9aab-1185f59c667b");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("008a45f7-f597-4450-9aab-1185f59c667b")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("008a45f7-f597-4450-9aab-1185f59c667b", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f23c72ce-b5d0-4689-8013-25a8ede3fc20")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f23c72ce-b5d0-4689-8013-25a8ede3fc20")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug11 item.
            /// </summary>
            [RepositoryItem("8cb21262-2505-4f11-bc9c-37b44d5df5ed")]
            public virtual Ranorex.TreeItem OptionPlan2011Aug11
            {
                get
                {
                    return _optionplan2011aug11Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OptionPlan2011Aug11 item info.
            /// </summary>
            [RepositoryItemInfo("8cb21262-2505-4f11-bc9c-37b44d5df5ed")]
            public virtual RepoItemInfo OptionPlan2011Aug11Info
            {
                get
                {
                    return _optionplan2011aug11Info;
                }
            }

            /// <summary>
            /// The Scroller1 item.
            /// </summary>
            [RepositoryItem("45f87eb2-451a-4b20-b821-ebdc685f345e")]
            public virtual Ranorex.TreeItem Scroller1
            {
                get
                {
                    return _scroller1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Scroller1 item info.
            /// </summary>
            [RepositoryItemInfo("45f87eb2-451a-4b20-b821-ebdc685f345e")]
            public virtual Scroller1InfoClass Scroller1Info
            {
                get
                {
                    return _scroller1Info;
                }
            }

            /// <summary>
            /// The Copy_of_Scroller1 item.
            /// </summary>
            [RepositoryItem("defb7b87-60ae-421d-a548-eb40b802e1da")]
            public virtual Ranorex.TreeItem Copy_of_Scroller1
            {
                get
                {
                    return _copy_of_scroller1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Copy_of_Scroller1 item info.
            /// </summary>
            [RepositoryItemInfo("defb7b87-60ae-421d-a548-eb40b802e1da")]
            public virtual Copy_of_Scroller1InfoClass Copy_of_Scroller1Info
            {
                get
                {
                    return _copy_of_scroller1Info;
                }
            }
        }

        /// <summary>
        /// The UltimateBotGamerIDDarrenDeluxeDaAppFolder folder.
        /// </summary>
        [RepositoryFolder("771f4671-c51b-4392-8c9f-061bc380314d")]
        public partial class UltimateBotGamerIDDarrenDeluxeDaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somelistInfo;

            /// <summary>
            /// Creates a new UltimateBotGamerIDDarrenDeluxeDa  folder.
            /// </summary>
            public UltimateBotGamerIDDarrenDeluxeDaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UltimateBotGamerIDDarrenDeluxeDa", "/form[@wpfnative='True' and @title='UltimateBot [Gamer ID: Darren Deluxe (darrenbrazeal@aol.com) | Club Name: FC NEYMARRED (FCN) | Coins: 110581 | Status: Sleep]  (Runtime: 02:27:57)' and @processname='UltimateBot']", parentFolder, 30000, null, true, "771f4671-c51b-4392-8c9f-061bc380314d", "")
            {
                _somelistInfo = new RepoItemInfo(this, "SomeList", "container[@automationid='PART_MainBorder' and @name='PART_MainBorder']/container[pos()=1]/container[@automationid='contentHost' and @name='contentHost']/container[pos()=11]/tabpagelist[pos()=1]/tabpage[@title='Players' and @index='0']/tabpagelist[pos()=0]/tabpage[@title='Player List (115) [You already earned -54000 coins!]' and @index='0']/container[pos()=0]/container[pos()=0]/list[pos()=1]", 30000, null, "78fb373f-f29a-407e-830d-eb6788268b35");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("771f4671-c51b-4392-8c9f-061bc380314d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("771f4671-c51b-4392-8c9f-061bc380314d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeList item.
            /// </summary>
            [RepositoryItem("78fb373f-f29a-407e-830d-eb6788268b35")]
            public virtual Ranorex.List SomeList
            {
                get
                {
                    return _somelistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The SomeList item info.
            /// </summary>
            [RepositoryItemInfo("78fb373f-f29a-407e-830d-eb6788268b35")]
            public virtual RepoItemInfo SomeListInfo
            {
                get
                {
                    return _somelistInfo;
                }
            }
        }

        /// <summary>
        /// The ScreencastOMaticAppFolder folder.
        /// </summary>
        [RepositoryFolder("d5e2a6cc-a326-4f39-9ed5-e99169ced137")]
        public partial class ScreencastOMaticAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contentpaneInfo;

            /// <summary>
            /// Creates a new ScreencastOMatic  folder.
            /// </summary>
            public ScreencastOMaticAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ScreencastOMatic", "/form[@processname='Screencast-O-Matic' and @class='SunAwtWindow' and @type='DraggableFrame$2$1']", parentFolder, 30000, null, false, "d5e2a6cc-a326-4f39-9ed5-e99169ced137", "")
            {
                _contentpaneInfo = new RepoItemInfo(this, "ContentPane", "container[@type='JRootPane' and @fulltype='javax.swing.JRootPane']/container[@name='null.layeredPane' and @type='JLayeredPane' and @fulltype='javax.swing.JLayeredPane']/container[@name='contentPane' and @type='DraggableFrame$3' and @fulltype='com.screencastomatic.display.DraggableFrame$3']", 30000, null, "f2f8d877-43d9-4de1-a80e-36d33f1893f1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d5e2a6cc-a326-4f39-9ed5-e99169ced137")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d5e2a6cc-a326-4f39-9ed5-e99169ced137")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContentPane item.
            /// </summary>
            [RepositoryItem("f2f8d877-43d9-4de1-a80e-36d33f1893f1")]
            public virtual Ranorex.Container ContentPane
            {
                get
                {
                    return _contentpaneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContentPane item info.
            /// </summary>
            [RepositoryItemInfo("f2f8d877-43d9-4de1-a80e-36d33f1893f1")]
            public virtual RepoItemInfo ContentPaneInfo
            {
                get
                {
                    return _contentpaneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}